### ISSUE TITLE
How to create a room map from the point clouds?

### ISSUE THREAD

**Issue by jamesbaker1** [npu-ius-lab/MoNA-Bench#1]
First of all, this project is awesome, and thank you for sharing your work. Given the point clouds from the monocular depth estimations, is it possible to create a 3d rendering of the room? If so, it is possible to overlay the actual camera pictures over the 3d rendering? Sorry if this question is too trivial! Thanks again.

**Comment by cavayangtao** [comment]
Hi @jamesbaker1,
many thanks for your interest in our work, and sorry for this very late reply.
In our current work, the point clouds are utilized for two purposes. First, the point clouds are used to segment the ground plane for scale recovery. The scale-recovered depth maps are then input to orb-slam2 to get odometry. Second, the scale-recovered point clouds are used to generate 3D dynamic grids for obstacle avoidance. 
3D rendering from monocular depth estimations is not covered in this work but an interesting question. The main difficulty is the scale uncertainty or scale instability of monocular depth estimations. Some recent work like DepthAnything provides the possibility of this task. Nerf also can be a solution.
